/*
 * ReloadlySdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.reloadly.auth.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RecipientPhoneDetails type.
 */
public class RecipientPhoneDetails {
    private String countryCode;
    private String phoneNumber;

    /**
     * Default constructor.
     */
    public RecipientPhoneDetails() {
    }

    /**
     * Initialization constructor.
     * @param  countryCode  String value for countryCode.
     * @param  phoneNumber  String value for phoneNumber.
     */
    public RecipientPhoneDetails(
            String countryCode,
            String phoneNumber) {
        this.countryCode = countryCode;
        this.phoneNumber = phoneNumber;
    }

    /**
     * Getter for CountryCode.
     * @return Returns the String
     */
    @JsonGetter("countryCode")
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Setter for CountryCode.
     * @param countryCode Value for String
     */
    @JsonSetter("countryCode")
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * Getter for PhoneNumber.
     * @return Returns the String
     */
    @JsonGetter("phoneNumber")
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Setter for PhoneNumber.
     * @param phoneNumber Value for String
     */
    @JsonSetter("phoneNumber")
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Converts this RecipientPhoneDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RecipientPhoneDetails [" + "countryCode=" + countryCode + ", phoneNumber="
                + phoneNumber + "]";
    }

    /**
     * Builds a new {@link RecipientPhoneDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RecipientPhoneDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(countryCode, phoneNumber);
        return builder;
    }

    /**
     * Class to build instances of {@link RecipientPhoneDetails}.
     */
    public static class Builder {
        private String countryCode;
        private String phoneNumber;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  countryCode  String value for countryCode.
         * @param  phoneNumber  String value for phoneNumber.
         */
        public Builder(String countryCode, String phoneNumber) {
            this.countryCode = countryCode;
            this.phoneNumber = phoneNumber;
        }

        /**
         * Setter for countryCode.
         * @param  countryCode  String value for countryCode.
         * @return Builder
         */
        public Builder countryCode(String countryCode) {
            this.countryCode = countryCode;
            return this;
        }

        /**
         * Setter for phoneNumber.
         * @param  phoneNumber  String value for phoneNumber.
         * @return Builder
         */
        public Builder phoneNumber(String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        /**
         * Builds a new {@link RecipientPhoneDetails} object using the set fields.
         * @return {@link RecipientPhoneDetails}
         */
        public RecipientPhoneDetails build() {
            return new RecipientPhoneDetails(countryCode, phoneNumber);
        }
    }
}
