/*
 * ReloadlySdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.reloadly.auth.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ReloadlyAuthRequest type.
 */
public class ReloadlyAuthRequest {
    private String clientId;
    private String clientSecret;
    private String grantType;
    private String audience;

    /**
     * Default constructor.
     */
    public ReloadlyAuthRequest() {
    }

    /**
     * Initialization constructor.
     * @param  clientId  String value for clientId.
     * @param  clientSecret  String value for clientSecret.
     * @param  grantType  String value for grantType.
     * @param  audience  String value for audience.
     */
    public ReloadlyAuthRequest(
            String clientId,
            String clientSecret,
            String grantType,
            String audience) {
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.grantType = grantType;
        this.audience = audience;
    }

    /**
     * Getter for ClientId.
     * @return Returns the String
     */
    @JsonGetter("client_id")
    public String getClientId() {
        return clientId;
    }

    /**
     * Setter for ClientId.
     * @param clientId Value for String
     */
    @JsonSetter("client_id")
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * Getter for ClientSecret.
     * @return Returns the String
     */
    @JsonGetter("client_secret")
    public String getClientSecret() {
        return clientSecret;
    }

    /**
     * Setter for ClientSecret.
     * @param clientSecret Value for String
     */
    @JsonSetter("client_secret")
    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }

    /**
     * Getter for GrantType.
     * @return Returns the String
     */
    @JsonGetter("grant_type")
    public String getGrantType() {
        return grantType;
    }

    /**
     * Setter for GrantType.
     * @param grantType Value for String
     */
    @JsonSetter("grant_type")
    public void setGrantType(String grantType) {
        this.grantType = grantType;
    }

    /**
     * Getter for Audience.
     * @return Returns the String
     */
    @JsonGetter("audience")
    public String getAudience() {
        return audience;
    }

    /**
     * Setter for Audience.
     * @param audience Value for String
     */
    @JsonSetter("audience")
    public void setAudience(String audience) {
        this.audience = audience;
    }

    /**
     * Converts this ReloadlyAuthRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ReloadlyAuthRequest [" + "clientId=" + clientId + ", clientSecret=" + clientSecret
                + ", grantType=" + grantType + ", audience=" + audience + "]";
    }

    /**
     * Builds a new {@link ReloadlyAuthRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ReloadlyAuthRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(clientId, clientSecret, grantType, audience);
        return builder;
    }

    /**
     * Class to build instances of {@link ReloadlyAuthRequest}.
     */
    public static class Builder {
        private String clientId;
        private String clientSecret;
        private String grantType;
        private String audience;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  clientId  String value for clientId.
         * @param  clientSecret  String value for clientSecret.
         * @param  grantType  String value for grantType.
         * @param  audience  String value for audience.
         */
        public Builder(String clientId, String clientSecret, String grantType, String audience) {
            this.clientId = clientId;
            this.clientSecret = clientSecret;
            this.grantType = grantType;
            this.audience = audience;
        }

        /**
         * Setter for clientId.
         * @param  clientId  String value for clientId.
         * @return Builder
         */
        public Builder clientId(String clientId) {
            this.clientId = clientId;
            return this;
        }

        /**
         * Setter for clientSecret.
         * @param  clientSecret  String value for clientSecret.
         * @return Builder
         */
        public Builder clientSecret(String clientSecret) {
            this.clientSecret = clientSecret;
            return this;
        }

        /**
         * Setter for grantType.
         * @param  grantType  String value for grantType.
         * @return Builder
         */
        public Builder grantType(String grantType) {
            this.grantType = grantType;
            return this;
        }

        /**
         * Setter for audience.
         * @param  audience  String value for audience.
         * @return Builder
         */
        public Builder audience(String audience) {
            this.audience = audience;
            return this;
        }

        /**
         * Builds a new {@link ReloadlyAuthRequest} object using the set fields.
         * @return {@link ReloadlyAuthRequest}
         */
        public ReloadlyAuthRequest build() {
            return new ReloadlyAuthRequest(clientId, clientSecret, grantType, audience);
        }
    }
}
