/*
 * ReloadlySdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.reloadly.auth.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ReloadlyAirtimeFxRatesRequest type.
 */
public class ReloadlyAirtimeFxRatesRequest {
    private String operatorId;
    private String amount;

    /**
     * Default constructor.
     */
    public ReloadlyAirtimeFxRatesRequest() {
    }

    /**
     * Initialization constructor.
     * @param  operatorId  String value for operatorId.
     * @param  amount  String value for amount.
     */
    public ReloadlyAirtimeFxRatesRequest(
            String operatorId,
            String amount) {
        this.operatorId = operatorId;
        this.amount = amount;
    }

    /**
     * Getter for OperatorId.
     * @return Returns the String
     */
    @JsonGetter("operatorId")
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * Setter for OperatorId.
     * @param operatorId Value for String
     */
    @JsonSetter("operatorId")
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * Getter for Amount.
     * @return Returns the String
     */
    @JsonGetter("amount")
    public String getAmount() {
        return amount;
    }

    /**
     * Setter for Amount.
     * @param amount Value for String
     */
    @JsonSetter("amount")
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * Converts this ReloadlyAirtimeFxRatesRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ReloadlyAirtimeFxRatesRequest [" + "operatorId=" + operatorId + ", amount=" + amount
                + "]";
    }

    /**
     * Builds a new {@link ReloadlyAirtimeFxRatesRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ReloadlyAirtimeFxRatesRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(operatorId, amount);
        return builder;
    }

    /**
     * Class to build instances of {@link ReloadlyAirtimeFxRatesRequest}.
     */
    public static class Builder {
        private String operatorId;
        private String amount;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  operatorId  String value for operatorId.
         * @param  amount  String value for amount.
         */
        public Builder(String operatorId, String amount) {
            this.operatorId = operatorId;
            this.amount = amount;
        }

        /**
         * Setter for operatorId.
         * @param  operatorId  String value for operatorId.
         * @return Builder
         */
        public Builder operatorId(String operatorId) {
            this.operatorId = operatorId;
            return this;
        }

        /**
         * Setter for amount.
         * @param  amount  String value for amount.
         * @return Builder
         */
        public Builder amount(String amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Builds a new {@link ReloadlyAirtimeFxRatesRequest} object using the set fields.
         * @return {@link ReloadlyAirtimeFxRatesRequest}
         */
        public ReloadlyAirtimeFxRatesRequest build() {
            return new ReloadlyAirtimeFxRatesRequest(operatorId, amount);
        }
    }
}
