/*
 * ReloadlySdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.reloadly.auth.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ReloadlyAirtimeAsyncTopupRequest type.
 */
public class ReloadlyAirtimeAsyncTopupRequest {
    private String operatorId;
    private String amount;
    private boolean useLocalAmount;
    private String customIdentifier;
    private RecipientPhone recipientPhone;
    private SenderPhone senderPhone;

    /**
     * Default constructor.
     */
    public ReloadlyAirtimeAsyncTopupRequest() {
    }

    /**
     * Initialization constructor.
     * @param  operatorId  String value for operatorId.
     * @param  amount  String value for amount.
     * @param  useLocalAmount  boolean value for useLocalAmount.
     * @param  customIdentifier  String value for customIdentifier.
     * @param  recipientPhone  RecipientPhone value for recipientPhone.
     * @param  senderPhone  SenderPhone value for senderPhone.
     */
    public ReloadlyAirtimeAsyncTopupRequest(
            String operatorId,
            String amount,
            boolean useLocalAmount,
            String customIdentifier,
            RecipientPhone recipientPhone,
            SenderPhone senderPhone) {
        this.operatorId = operatorId;
        this.amount = amount;
        this.useLocalAmount = useLocalAmount;
        this.customIdentifier = customIdentifier;
        this.recipientPhone = recipientPhone;
        this.senderPhone = senderPhone;
    }

    /**
     * Getter for OperatorId.
     * @return Returns the String
     */
    @JsonGetter("operatorId")
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * Setter for OperatorId.
     * @param operatorId Value for String
     */
    @JsonSetter("operatorId")
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * Getter for Amount.
     * @return Returns the String
     */
    @JsonGetter("amount")
    public String getAmount() {
        return amount;
    }

    /**
     * Setter for Amount.
     * @param amount Value for String
     */
    @JsonSetter("amount")
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * Getter for UseLocalAmount.
     * @return Returns the boolean
     */
    @JsonGetter("useLocalAmount")
    public boolean getUseLocalAmount() {
        return useLocalAmount;
    }

    /**
     * Setter for UseLocalAmount.
     * @param useLocalAmount Value for boolean
     */
    @JsonSetter("useLocalAmount")
    public void setUseLocalAmount(boolean useLocalAmount) {
        this.useLocalAmount = useLocalAmount;
    }

    /**
     * Getter for CustomIdentifier.
     * @return Returns the String
     */
    @JsonGetter("customIdentifier")
    public String getCustomIdentifier() {
        return customIdentifier;
    }

    /**
     * Setter for CustomIdentifier.
     * @param customIdentifier Value for String
     */
    @JsonSetter("customIdentifier")
    public void setCustomIdentifier(String customIdentifier) {
        this.customIdentifier = customIdentifier;
    }

    /**
     * Getter for RecipientPhone.
     * @return Returns the RecipientPhone
     */
    @JsonGetter("recipientPhone")
    public RecipientPhone getRecipientPhone() {
        return recipientPhone;
    }

    /**
     * Setter for RecipientPhone.
     * @param recipientPhone Value for RecipientPhone
     */
    @JsonSetter("recipientPhone")
    public void setRecipientPhone(RecipientPhone recipientPhone) {
        this.recipientPhone = recipientPhone;
    }

    /**
     * Getter for SenderPhone.
     * @return Returns the SenderPhone
     */
    @JsonGetter("senderPhone")
    public SenderPhone getSenderPhone() {
        return senderPhone;
    }

    /**
     * Setter for SenderPhone.
     * @param senderPhone Value for SenderPhone
     */
    @JsonSetter("senderPhone")
    public void setSenderPhone(SenderPhone senderPhone) {
        this.senderPhone = senderPhone;
    }

    /**
     * Converts this ReloadlyAirtimeAsyncTopupRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ReloadlyAirtimeAsyncTopupRequest [" + "operatorId=" + operatorId + ", amount="
                + amount + ", useLocalAmount=" + useLocalAmount + ", customIdentifier="
                + customIdentifier + ", recipientPhone=" + recipientPhone + ", senderPhone="
                + senderPhone + "]";
    }

    /**
     * Builds a new {@link ReloadlyAirtimeAsyncTopupRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ReloadlyAirtimeAsyncTopupRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(operatorId, amount, useLocalAmount, customIdentifier,
                recipientPhone, senderPhone);
        return builder;
    }

    /**
     * Class to build instances of {@link ReloadlyAirtimeAsyncTopupRequest}.
     */
    public static class Builder {
        private String operatorId;
        private String amount;
        private boolean useLocalAmount;
        private String customIdentifier;
        private RecipientPhone recipientPhone;
        private SenderPhone senderPhone;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  operatorId  String value for operatorId.
         * @param  amount  String value for amount.
         * @param  useLocalAmount  boolean value for useLocalAmount.
         * @param  customIdentifier  String value for customIdentifier.
         * @param  recipientPhone  RecipientPhone value for recipientPhone.
         * @param  senderPhone  SenderPhone value for senderPhone.
         */
        public Builder(String operatorId, String amount, boolean useLocalAmount,
                String customIdentifier, RecipientPhone recipientPhone, SenderPhone senderPhone) {
            this.operatorId = operatorId;
            this.amount = amount;
            this.useLocalAmount = useLocalAmount;
            this.customIdentifier = customIdentifier;
            this.recipientPhone = recipientPhone;
            this.senderPhone = senderPhone;
        }

        /**
         * Setter for operatorId.
         * @param  operatorId  String value for operatorId.
         * @return Builder
         */
        public Builder operatorId(String operatorId) {
            this.operatorId = operatorId;
            return this;
        }

        /**
         * Setter for amount.
         * @param  amount  String value for amount.
         * @return Builder
         */
        public Builder amount(String amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Setter for useLocalAmount.
         * @param  useLocalAmount  boolean value for useLocalAmount.
         * @return Builder
         */
        public Builder useLocalAmount(boolean useLocalAmount) {
            this.useLocalAmount = useLocalAmount;
            return this;
        }

        /**
         * Setter for customIdentifier.
         * @param  customIdentifier  String value for customIdentifier.
         * @return Builder
         */
        public Builder customIdentifier(String customIdentifier) {
            this.customIdentifier = customIdentifier;
            return this;
        }

        /**
         * Setter for recipientPhone.
         * @param  recipientPhone  RecipientPhone value for recipientPhone.
         * @return Builder
         */
        public Builder recipientPhone(RecipientPhone recipientPhone) {
            this.recipientPhone = recipientPhone;
            return this;
        }

        /**
         * Setter for senderPhone.
         * @param  senderPhone  SenderPhone value for senderPhone.
         * @return Builder
         */
        public Builder senderPhone(SenderPhone senderPhone) {
            this.senderPhone = senderPhone;
            return this;
        }

        /**
         * Builds a new {@link ReloadlyAirtimeAsyncTopupRequest} object using the set fields.
         * @return {@link ReloadlyAirtimeAsyncTopupRequest}
         */
        public ReloadlyAirtimeAsyncTopupRequest build() {
            return new ReloadlyAirtimeAsyncTopupRequest(operatorId, amount, useLocalAmount,
                    customIdentifier, recipientPhone, senderPhone);
        }
    }
}
