/*
 * ReloadlySdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.reloadly.auth.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ReloadlyNumberLookupPostRequest type.
 */
public class ReloadlyNumberLookupPostRequest {
    private String number;
    private String countryCode;

    /**
     * Default constructor.
     */
    public ReloadlyNumberLookupPostRequest() {
    }

    /**
     * Initialization constructor.
     * @param  number  String value for number.
     * @param  countryCode  String value for countryCode.
     */
    public ReloadlyNumberLookupPostRequest(
            String number,
            String countryCode) {
        this.number = number;
        this.countryCode = countryCode;
    }

    /**
     * Getter for Number.
     * @return Returns the String
     */
    @JsonGetter("number")
    public String getNumber() {
        return number;
    }

    /**
     * Setter for Number.
     * @param number Value for String
     */
    @JsonSetter("number")
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * Getter for CountryCode.
     * @return Returns the String
     */
    @JsonGetter("countryCode")
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Setter for CountryCode.
     * @param countryCode Value for String
     */
    @JsonSetter("countryCode")
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * Converts this ReloadlyNumberLookupPostRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ReloadlyNumberLookupPostRequest [" + "number=" + number + ", countryCode="
                + countryCode + "]";
    }

    /**
     * Builds a new {@link ReloadlyNumberLookupPostRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ReloadlyNumberLookupPostRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(number, countryCode);
        return builder;
    }

    /**
     * Class to build instances of {@link ReloadlyNumberLookupPostRequest}.
     */
    public static class Builder {
        private String number;
        private String countryCode;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  number  String value for number.
         * @param  countryCode  String value for countryCode.
         */
        public Builder(String number, String countryCode) {
            this.number = number;
            this.countryCode = countryCode;
        }

        /**
         * Setter for number.
         * @param  number  String value for number.
         * @return Builder
         */
        public Builder number(String number) {
            this.number = number;
            return this;
        }

        /**
         * Setter for countryCode.
         * @param  countryCode  String value for countryCode.
         * @return Builder
         */
        public Builder countryCode(String countryCode) {
            this.countryCode = countryCode;
            return this;
        }

        /**
         * Builds a new {@link ReloadlyNumberLookupPostRequest} object using the set fields.
         * @return {@link ReloadlyNumberLookupPostRequest}
         */
        public ReloadlyNumberLookupPostRequest build() {
            return new ReloadlyNumberLookupPostRequest(number, countryCode);
        }
    }
}
