/*
 * ReloadlySdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.reloadly.auth.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ReloadlyGiftCardsOrdersRequest type.
 */
public class ReloadlyGiftCardsOrdersRequest {
    private int productId;
    private String countryCode;
    private int quantity;
    private int unitPrice;
    private String customIdentifier;
    private String senderName;
    private String recipientEmail;
    private RecipientPhoneDetails recipientPhoneDetails;

    /**
     * Default constructor.
     */
    public ReloadlyGiftCardsOrdersRequest() {
    }

    /**
     * Initialization constructor.
     * @param  productId  int value for productId.
     * @param  countryCode  String value for countryCode.
     * @param  quantity  int value for quantity.
     * @param  unitPrice  int value for unitPrice.
     * @param  customIdentifier  String value for customIdentifier.
     * @param  senderName  String value for senderName.
     * @param  recipientEmail  String value for recipientEmail.
     * @param  recipientPhoneDetails  RecipientPhoneDetails value for recipientPhoneDetails.
     */
    public ReloadlyGiftCardsOrdersRequest(
            int productId,
            String countryCode,
            int quantity,
            int unitPrice,
            String customIdentifier,
            String senderName,
            String recipientEmail,
            RecipientPhoneDetails recipientPhoneDetails) {
        this.productId = productId;
        this.countryCode = countryCode;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
        this.customIdentifier = customIdentifier;
        this.senderName = senderName;
        this.recipientEmail = recipientEmail;
        this.recipientPhoneDetails = recipientPhoneDetails;
    }

    /**
     * Getter for ProductId.
     * @return Returns the int
     */
    @JsonGetter("productId")
    public int getProductId() {
        return productId;
    }

    /**
     * Setter for ProductId.
     * @param productId Value for int
     */
    @JsonSetter("productId")
    public void setProductId(int productId) {
        this.productId = productId;
    }

    /**
     * Getter for CountryCode.
     * @return Returns the String
     */
    @JsonGetter("countryCode")
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Setter for CountryCode.
     * @param countryCode Value for String
     */
    @JsonSetter("countryCode")
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * Getter for Quantity.
     * @return Returns the int
     */
    @JsonGetter("quantity")
    public int getQuantity() {
        return quantity;
    }

    /**
     * Setter for Quantity.
     * @param quantity Value for int
     */
    @JsonSetter("quantity")
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    /**
     * Getter for UnitPrice.
     * @return Returns the int
     */
    @JsonGetter("unitPrice")
    public int getUnitPrice() {
        return unitPrice;
    }

    /**
     * Setter for UnitPrice.
     * @param unitPrice Value for int
     */
    @JsonSetter("unitPrice")
    public void setUnitPrice(int unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * Getter for CustomIdentifier.
     * @return Returns the String
     */
    @JsonGetter("customIdentifier")
    public String getCustomIdentifier() {
        return customIdentifier;
    }

    /**
     * Setter for CustomIdentifier.
     * @param customIdentifier Value for String
     */
    @JsonSetter("customIdentifier")
    public void setCustomIdentifier(String customIdentifier) {
        this.customIdentifier = customIdentifier;
    }

    /**
     * Getter for SenderName.
     * @return Returns the String
     */
    @JsonGetter("senderName")
    public String getSenderName() {
        return senderName;
    }

    /**
     * Setter for SenderName.
     * @param senderName Value for String
     */
    @JsonSetter("senderName")
    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    /**
     * Getter for RecipientEmail.
     * @return Returns the String
     */
    @JsonGetter("recipientEmail")
    public String getRecipientEmail() {
        return recipientEmail;
    }

    /**
     * Setter for RecipientEmail.
     * @param recipientEmail Value for String
     */
    @JsonSetter("recipientEmail")
    public void setRecipientEmail(String recipientEmail) {
        this.recipientEmail = recipientEmail;
    }

    /**
     * Getter for RecipientPhoneDetails.
     * @return Returns the RecipientPhoneDetails
     */
    @JsonGetter("recipientPhoneDetails")
    public RecipientPhoneDetails getRecipientPhoneDetails() {
        return recipientPhoneDetails;
    }

    /**
     * Setter for RecipientPhoneDetails.
     * @param recipientPhoneDetails Value for RecipientPhoneDetails
     */
    @JsonSetter("recipientPhoneDetails")
    public void setRecipientPhoneDetails(RecipientPhoneDetails recipientPhoneDetails) {
        this.recipientPhoneDetails = recipientPhoneDetails;
    }

    /**
     * Converts this ReloadlyGiftCardsOrdersRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ReloadlyGiftCardsOrdersRequest [" + "productId=" + productId + ", countryCode="
                + countryCode + ", quantity=" + quantity + ", unitPrice=" + unitPrice
                + ", customIdentifier=" + customIdentifier + ", senderName=" + senderName
                + ", recipientEmail=" + recipientEmail + ", recipientPhoneDetails="
                + recipientPhoneDetails + "]";
    }

    /**
     * Builds a new {@link ReloadlyGiftCardsOrdersRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ReloadlyGiftCardsOrdersRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(productId, countryCode, quantity, unitPrice, customIdentifier,
                senderName, recipientEmail, recipientPhoneDetails);
        return builder;
    }

    /**
     * Class to build instances of {@link ReloadlyGiftCardsOrdersRequest}.
     */
    public static class Builder {
        private int productId;
        private String countryCode;
        private int quantity;
        private int unitPrice;
        private String customIdentifier;
        private String senderName;
        private String recipientEmail;
        private RecipientPhoneDetails recipientPhoneDetails;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  productId  int value for productId.
         * @param  countryCode  String value for countryCode.
         * @param  quantity  int value for quantity.
         * @param  unitPrice  int value for unitPrice.
         * @param  customIdentifier  String value for customIdentifier.
         * @param  senderName  String value for senderName.
         * @param  recipientEmail  String value for recipientEmail.
         * @param  recipientPhoneDetails  RecipientPhoneDetails value for recipientPhoneDetails.
         */
        public Builder(int productId, String countryCode, int quantity, int unitPrice,
                String customIdentifier, String senderName, String recipientEmail,
                RecipientPhoneDetails recipientPhoneDetails) {
            this.productId = productId;
            this.countryCode = countryCode;
            this.quantity = quantity;
            this.unitPrice = unitPrice;
            this.customIdentifier = customIdentifier;
            this.senderName = senderName;
            this.recipientEmail = recipientEmail;
            this.recipientPhoneDetails = recipientPhoneDetails;
        }

        /**
         * Setter for productId.
         * @param  productId  int value for productId.
         * @return Builder
         */
        public Builder productId(int productId) {
            this.productId = productId;
            return this;
        }

        /**
         * Setter for countryCode.
         * @param  countryCode  String value for countryCode.
         * @return Builder
         */
        public Builder countryCode(String countryCode) {
            this.countryCode = countryCode;
            return this;
        }

        /**
         * Setter for quantity.
         * @param  quantity  int value for quantity.
         * @return Builder
         */
        public Builder quantity(int quantity) {
            this.quantity = quantity;
            return this;
        }

        /**
         * Setter for unitPrice.
         * @param  unitPrice  int value for unitPrice.
         * @return Builder
         */
        public Builder unitPrice(int unitPrice) {
            this.unitPrice = unitPrice;
            return this;
        }

        /**
         * Setter for customIdentifier.
         * @param  customIdentifier  String value for customIdentifier.
         * @return Builder
         */
        public Builder customIdentifier(String customIdentifier) {
            this.customIdentifier = customIdentifier;
            return this;
        }

        /**
         * Setter for senderName.
         * @param  senderName  String value for senderName.
         * @return Builder
         */
        public Builder senderName(String senderName) {
            this.senderName = senderName;
            return this;
        }

        /**
         * Setter for recipientEmail.
         * @param  recipientEmail  String value for recipientEmail.
         * @return Builder
         */
        public Builder recipientEmail(String recipientEmail) {
            this.recipientEmail = recipientEmail;
            return this;
        }

        /**
         * Setter for recipientPhoneDetails.
         * @param  recipientPhoneDetails  RecipientPhoneDetails value for recipientPhoneDetails.
         * @return Builder
         */
        public Builder recipientPhoneDetails(RecipientPhoneDetails recipientPhoneDetails) {
            this.recipientPhoneDetails = recipientPhoneDetails;
            return this;
        }

        /**
         * Builds a new {@link ReloadlyGiftCardsOrdersRequest} object using the set fields.
         * @return {@link ReloadlyGiftCardsOrdersRequest}
         */
        public ReloadlyGiftCardsOrdersRequest build() {
            return new ReloadlyGiftCardsOrdersRequest(productId, countryCode, quantity, unitPrice,
                    customIdentifier, senderName, recipientEmail, recipientPhoneDetails);
        }
    }
}
