/*
 * ReloadlySdkLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.reloadly.auth;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Server to be used.
 */
public enum Server {
    AUTHENTICATION,

    GIFT_CARDS,

    UTILITY_PAYMENTS,

    AIRTIME;


    private static TreeMap<String, Server> valueMap = new TreeMap<>();
    private String value;

    static {
        AUTHENTICATION.value = "Authentication";
        GIFT_CARDS.value = "Gift Cards";
        UTILITY_PAYMENTS.value = "Utility Payments";
        AIRTIME.value = "Airtime";

        valueMap.put("Authentication", AUTHENTICATION);
        valueMap.put("Gift Cards", GIFT_CARDS);
        valueMap.put("Utility Payments", UTILITY_PAYMENTS);
        valueMap.put("Airtime", AIRTIME);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static Server fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Server values to list of string values.
     * @param toConvert The list of Server values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Server> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Server enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 